; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = ststm32
board = nucleo_f446re
framework = cmsis
build_flags = 
  -mfpu=fpv4-sp-d16
  -mfloat-abi=softfp

[env:f446re]
build_src_filter =
  -<*>
  +<rtos/>
  +<boards/f446re/>
  +<demos/showcase/>

[env:f446re_priority]
build_src_filter =
  -<*>
  +<rtos/>
  +<boards/f446re/>
  +<demos/priority/>

[env:f446re_mutex]
build_src_filter =
  -<*>
  +<rtos/>
  +<boards/f446re/>
  +<demos/mutex/>

[env:nucleo_f446re_test]
test_framework = unity
test_build_src = yes
test_speed = 115200
build_src_filter =
  -<*>
  +<rtos/>

[platformio]
default_envs = f446re

[env:l4s5i]
platform = ststm32
board = disco_l4s5i_iot01a
framework = stm32cube
build_src_filter =
  -<*>
  +<rtos/>
  +<boards/l4s5i/>
  +<demos/showcase/>

[env:l4s5i_priority]
platform = ststm32
board = disco_l4s5i_iot01a
framework = stm32cube
build_src_filter =
  -<*>
  +<rtos/>
  +<boards/l4s5i/>
  +<demos/priority/>

[env:l4s5i_mutex]
platform = ststm32
board = disco_l4s5i_iot01a
framework = stm32cube
build_src_filter =
  -<*>
  +<rtos/>
  +<boards/l4s5i/>
  +<demos/mutex/>
