#ifndef ARTOS_CONFIG_H
#define ARTOS_CONFIG_H

#define ARTOS_MAX_TASKS 16U
#define ARTOS_TICK_HZ 1000U
#define ARTOS_PRIORITY_COUNT 2U
#define ARTOS_ENABLE_ASSERTS 1
#define ARTOS_DEBUG_BREAK_ON_FAILURE 1
#define ARTOS_CPU_CLOCK_HZ 16000000UL

// Recommend to increase this to 128U if floating point is used
// MUST BE MULTIPLE OF 8
#define ARTOS_MIN_STACK_WORDS 64U

#endif // !ARTOS_CONFIG_H
